main: cn.sky.luckypillar.SkyLuckyPillar
version: 1.0.2
name: SkyLuckyPillar
author: pi_ka
api-version: 1.13
commands:
  luckypillar:
    description: "Lucky Pillar Main Command"
    aliases: ["lpillar", "pillar"]
